export const TICKETS_HAS_ERRORED= 'TICKETS_HAS_ERRORED';
export const TICKETS_IS_LOADING = 'TICKETS_IS_LOADING';
export const TICKETS_FETCH_DATA_SUCCESS = 'TICKETS_FETCH_DATA_SUCCESS';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CHANGE_SELECTED_TICKET_ID = 'CHANGE_SELECTED_TICKET_ID';
export const DELETE_TICKET = 'DELETE_TICKET';
export const ADD_TICKET = 'ADD_TICKET';
